ini_open("config");
global.faz_coin = ini_read_real("faz-coins", "", 0);
global.fridge = ini_read_real("fridge", "", 0);
global.coin = ini_read_real("coin", "", 0);
global.battery = ini_read_real("battery", "", 0);
global.dd_repel = ini_read_real("dd_repel", "", 0);
global.message = ini_read_string("message", "", "false");
global.message_ddlc = ini_read_string("message_ddlc", "", "false");
global.GJ_name = ini_read_string("GJ_User", "", "");
global.GJ_pass = ini_read_string("GJ_token", "", "");
global.office = ini_read_string("office", "", "Office");
global.theme = ini_read_string("theme", "", "UCN");
global.highscore = ini_read_real("H-S", "", 0);
global.hs_indie = ini_read_real("H-S_Indie", "", 0);
global.hs_ucn = ini_read_real("H-S_ucn", "", 0);
global.hs_reject = ini_read_real("H-S_reject", "", 0);
global.debug = ini_read_string("Debug", "", "off");
global.gj_user = ini_read_string("gj_user", "", "");
global.gj_token = ini_read_string("gj_token", "", "");
global.message_tease = ini_read_string("message_tease", "", "false");
global.merge = ini_read_real("Merge_Mode", "", 0);
global.screen = ini_read_string("screen","","on");
global.m_name = ini_read_string("m_name","","Player");
global.theme_mode = ini_read_real("theme_mode","",0);
global.theme_used = ini_read_real("theme_used","",0);
global.theme1_name = ini_read_string("theme","theme1","Theme 1");
global.theme2_name = ini_read_string("theme","theme2","Theme 2");
global.theme3_name = ini_read_string("theme","theme3","Theme 3");
global.theme4_name = ini_read_string("theme","theme4","Theme 4");
///Challenge
global.doki1 = ini_read_string("doki1", "", "false");
global.doki2 = ini_read_string("doki2", "", "false");
global.doki3 = ini_read_string("doki3", "", "false");
ini_close();